"use strict";
const HB_KEY="herria_langue";
const HB_DEFAULT="fr";
const HB_HISTORY=true;
const HB_TRANSLATIONS={"eu": {"← retour à l’accueil": "← harrera-orrira itzuli", "haut de page ↑": "orriaren gaina ↑", "Histoire des Basques — Herria Bihotzean": "Eskualdunen istoria — Herria Bihotzean"}, "be": {"← retour à l’accueil": "← tourna à l’acuèlh", "haut de page ↑": "cap de pagine ↑", "Histoire des Basques — Herria Bihotzean": "Istoère deus Bàscous — Herria Bihotzean"}};
const HB_LABELS={"fr": {"fr": "français", "eu": "basque", "be": "béarnais"}, "eu": {"fr": "frantsesez", "eu": "eskuaraz", "be": "biarnesez"}, "be": {"fr": "francés", "eu": "bascou", "be": "biarnés"}};
function hbGeneralLanguage(){const l=localStorage.getItem(HB_KEY);return l==="eu"?"eu":"fr";}
function hbCurrentLanguage(){if(HB_HISTORY){const s=sessionStorage.getItem("herria_histoire_langue");if(["fr","eu","be"].includes(s))return s;}return hbGeneralLanguage();}
function hbLookup(text,lang){if(lang==="fr")return text;const clean=text.trim();const dict=HB_TRANSLATIONS[lang]||{};if(dict[clean])return text.replace(clean,dict[clean]);const m=clean.match(/^(\d+\.\s*)(.+)$/);if(m&&dict[m[2]])return text.replace(clean,m[1]+dict[m[2]]);return text;}
function hbTranslateNode(root=document.body,lang=hbCurrentLanguage()){
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
 nodes.forEach(n=>{if(!n.parentElement||["SCRIPT","STYLE","TEXTAREA"].includes(n.parentElement.tagName))return;if(n.parentElement.closest('.language-switcher'))return;const original=n.__hbOriginal??n.nodeValue;n.__hbOriginal=original;n.nodeValue=lang==="fr"?original:hbLookup(original,lang);});
 root.querySelectorAll?.('[placeholder],[title],[aria-label],[alt]').forEach(el=>{for(const a of ['placeholder','title','aria-label','alt']){if(!el.hasAttribute(a))continue;const k='hbOriginal'+a;el.dataset[k]=el.dataset[k]||el.getAttribute(a);el.setAttribute(a,lang==="fr"?el.dataset[k]:hbLookup(el.dataset[k],lang));}});
 document.documentElement.lang=lang==="eu"?"eu":lang==="be"?"oc":"fr";
 const t=document.querySelector('title');if(t){t.dataset.hbOriginal=t.dataset.hbOriginal||t.textContent;t.textContent=lang==="fr"?t.dataset.hbOriginal:hbLookup(t.dataset.hbOriginal,lang);}
}
function hbBuildSwitcher(){if(document.querySelector('.language-switcher'))return;const nav=document.createElement('nav');nav.className='language-switcher';nav.setAttribute('aria-label','Choix de la langue');const langs=HB_HISTORY?['fr','eu','be']:['fr','eu'];const imgs={fr:"blason-labourd.gif",eu:"blason-basse-navarre.gif",be:"blason-bearn.svg"};for(const l of langs){const b=document.createElement('button');b.type='button';b.className='language-choice';b.dataset.lang=l;b.innerHTML=`<img src="${imgs[l]}" alt=""><span></span>`;b.addEventListener('click',()=>hbSetLanguage(l));nav.appendChild(b);}document.body.insertBefore(nav,document.body.firstChild);}
function hbUpdateButtons(lang){document.querySelectorAll('.language-choice').forEach(b=>{b.querySelector('span').textContent=HB_LABELS[lang][b.dataset.lang];b.classList.toggle('active',b.dataset.lang===lang);b.setAttribute('aria-pressed',b.dataset.lang===lang?'true':'false');});}
function hbSetLanguage(lang){if(HB_HISTORY){sessionStorage.setItem('herria_histoire_langue',lang);if(lang!=='be')localStorage.setItem(HB_KEY,lang);document.querySelectorAll('[data-history-lang]').forEach(s=>s.hidden=s.dataset.historyLang!==lang);}else{localStorage.setItem(HB_KEY,lang);}hbTranslateNode(document.body,lang);hbUpdateButtons(lang);document.dispatchEvent(new CustomEvent('herria-language-change',{detail:{lang}}));}
document.addEventListener('DOMContentLoaded',()=>{hbBuildSwitcher();let lang=hbCurrentLanguage();if(HB_HISTORY)document.querySelectorAll('[data-history-lang]').forEach(s=>s.hidden=s.dataset.historyLang!==lang);hbTranslateNode(document.body,lang);hbUpdateButtons(lang);const obs=new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1||n.nodeType===3)hbTranslateNode(n.nodeType===1?n:n.parentElement,lang);});obs.observe(document.body,{childList:true,subtree:true});document.addEventListener('herria-language-change',e=>lang=e.detail.lang);});
